---
title: "Data Import"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(haven)
```

##Load in Litters dataset
```{r}
##read in a dataset 
litters_data = read_csv(file= "./data_import/FAS_litters.csv")
litters_data= janitor::clean_names(litters_data)
```

## Load in pups data 

```{r}
pups_data = read_csv(file ="./data_import/FAS_pups.csv")
pups_data= janitor::clean_names(litters_data)
```

##Play with column parsig

```{r}
litters_data = read_csv(file = "./data_import/FAS_litters.csv",
  col_types = cols(
     Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  ))
tail(litters_data)
```

## Read in an excel file...

```{r}
mlb11_data = read_excel(
  path="./data_import/mlb11.xlsx",
  range="A1:D7")
```

##Read in a SAS file...

```{r}
pulse_data = read_sas("./data_import/public_pulse_data.sas7bdat")
```

