---
title: "Data Manipulation"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

##Import dataset
```{r}
##read in a dataset 
litters_data = read_csv(file= "./data_import/FAS_litters.csv")
litters_data= janitor::clean_names(litters_data)
pups_data = read_csv(file ="./data_import/FAS_pups.csv")
pups_data= janitor::clean_names(pups_data)
```

## Selecting

```{r}
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight)

select(litters_data, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight)

select(litters_data, litter_number, group, everything())

select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_born_alive)

select(litters_data, GROUP= group, litter_number)

rename(litters_data, GROUP=group)
```



## Filtering

```{r}
filter(litters_data, group=="Mod8")

filter(litters_data, gd_of_birth==20)

filter(litters_data, gd_of_birth<20)

filter(litters_data, group=="con7" & gd_of_birth<20)

##filter(litters_data, group=="con7" | group== "mod8")
filter(litters_data, group %in% c("con7", "mod8"))

filter(litters_data, pups_born_alive>=4, pups_born_alive<=6)
##only complete cases
drop_na(litters_data)
##deletes only cases with missing gdo weight variables
drop_na(litters_data, gd0_weight)
```
 
 ##mutate
 
```{r}
mutate(
  litters_data, 
  wt_gain=gd18_weight-gd0_weight,
  group=str_to_lower(group)
  )

```
 
##Arrange

```{r}
arrange(litters_data, pups_born_alive)
arrange(litters_data, desc(pups_born_alive))
arrange(litters_data, pups_born_alive, gd0_weight)
```

##pipe

```{r}
litters_data = 
  read_csv("./data_import/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  # select(pups_survive) %>% 
   mutate(wt_gain = gd18_weight - gd0_weight,
   group = str_to_lower(group)) %>% 
   drop_na(wt_gain)
```

